INSERT INTO BE_ORDER(ID, AMOUNT, OWNER, PRODUCT, QUANTITY) VALUES (  50, 1100.99, 'Alice', 'Food', 10);
INSERT INTO BE_ORDER(ID, AMOUNT, OWNER, PRODUCT, QUANTITY) VALUES ( 100,  450.00, 'Alice', 'Golden Ring', 10);
INSERT INTO BE_ORDER(ID, AMOUNT, OWNER, PRODUCT, QUANTITY) VALUES ( 105,  500.50, 'Alice', 'Ring with diamonds', 5);
INSERT INTO BE_ORDER(ID, AMOUNT, OWNER, PRODUCT, QUANTITY) VALUES ( 110,  250.00, 'Alice', 'Ring', 1);
INSERT INTO BE_ORDER(ID, AMOUNT, OWNER, PRODUCT, QUANTITY) VALUES ( 200, 1200.99, 'Alice', 'Motorbike', 1);
INSERT INTO BE_ORDER(ID, AMOUNT, OWNER, PRODUCT, QUANTITY) VALUES ( 300, 1300.99, 'Alice', 'Dogfood', 1);
INSERT INTO BE_ORDER(ID, AMOUNT, OWNER, PRODUCT, QUANTITY) VALUES ( 400, 1400.99, 'Alice', 'Fork', 1);
INSERT INTO BE_ORDER(ID, AMOUNT, OWNER, PRODUCT, QUANTITY) VALUES ( 600, 1600.99, 'Cathy', 'Dogfood', 1);
INSERT INTO BE_ORDER(ID, AMOUNT, OWNER, PRODUCT, QUANTITY) VALUES (1000, 1968.05, 'Admin', 'Computer', 1);